name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CI: false
jobs:

  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15
        uses: actions/setup-node@v2
        with:
          node-version: 15
      - name: npm ci, build and test
        run: |
          npm ci
          npm run build --if-present
          npm test
