name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CI: false
jobs:

  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15
        uses: actions/setup-node@v2
        with:
          node-version: 15
      - name: run tests
        run: |
          npm ci
          npm run generate::secret
          npm test
